_target_: src.models.image_captioner.ImageCaptioner
name: "resnet50_attention_lstm"

encoder:
  _target_: src.models.components.resnet_encoder.ResNet50Encoder
  embed_size: 512
  pretrained: true
  freeze: true

decoder:
  _target_: src.models.components.attention_gru_decoder.AttentionGRUDecoder
  embed_size: 512
  hidden_size: 512
  vocab_size: ???
  attention_dim: 512
  num_layers: 3
  dropout: 0.5

vocab_size: ???
pad_idx: 0

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0005  # Lower LR for attention models
  weight_decay: 0.0001

