# Debug configuration for quick runs with profiling
defaults:
  - train

trainer:
  max_epochs: 1
  limit_train_batches: 20
  limit_val_batches: 10
  profiler: "pytorch" # You can change this to "simple" or "advanced" for less detailed profiling
